import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { createClient } from "@sanity/client";
import { Resend } from "resend";
dotenv.config();

const app = express();
const PORT = 5000;

// ✅ Middleware
app.use(cors());
app.use(express.json());

// ✅ Setup Sanity client
const sanity = createClient({
  projectId: "rewsmzz2",
  dataset: "production",
  useCdn: false,
  apiVersion: "2023-01-01",
  token: process.env.SANITY_WRITE_TOKEN,
});

const resend = new Resend(process.env.RESEND_API_KEY);

// ✅ Booking endpoint
app.post("/api/bookings", async (req, res) => {
  try {
    const {
      name,
      phone,
      email,
      serviceType,
      pickupLocation,
      dropoffLocation,
      vehicleDetails,
    } = req.body;

    // Basic validation
    if (!name || !phone || !email) {
      return res
        .status(400)
        .json({ success: false, error: "Missing required fields" });
    }

    // Save to Sanity
    const doc = {
      _type: "booking",
      name,
      phone,
      email,
      serviceType,
      pickupLocation,
      dropoffLocation,
      vehicleDetails,
      createdAt: new Date().toISOString(),
    };

    const result = await sanity.create(doc);

    // Send email via Resend
    await resend.emails.send({
      from: "Rapid Auto Rescue <rapidautorescue@resend.dev>",
      to: "autosaleslogisticsltd@gmail.com",
      subject: "🚨 New Booking Request Received",
      html: `
          <div style="font-family: Arial, sans-serif; padding: 24px; background-color: #f9fafb; color: #111827;">
            <img src="https://res.cloudinary.com/dmvd50ydu/image/upload/v1751306309/logo-fortune_waav9u.png" alt="Rapid Auto Rescue" style="width: 150px; margin-bottom: 20px;" />
            <h2 style="color: #1f2937;">New Booking Request</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Phone:</strong> ${phone}</p>
            <p><strong>Service Type:</strong> ${serviceType}</p>
            <p><strong>Pickup Location:</strong> ${pickupLocation}</p>
            <p><strong>Drop-off Location:</strong> ${dropoffLocation}</p>
            <p><strong>Vehicle Details:</strong> ${vehicleDetails || "N/A"}</p>
            <hr style="margin: 20px 0;" />
            <p style="font-size: 14px; color: #6b7280;">Submitted via <a href="https://www.rapidautorescue.co.uk" style="color: #2563eb;">RapidAutoRescue.co.uk</a> on ${new Date().toLocaleString()}</p>
          </div>
        `,
    });

    return res.status(201).json({ success: true, data: result });
  } catch (error) {
    console.error("❌ Booking error:", error.message);
    return res
      .status(500)
      .json({ success: false, error: "Internal server error" });
  }
});

app.post("/api/quotes", async (req, res) => {
  const { fullName, phoneNumber, serviceRequired, additionalInfo } = req.body;

  try {
    // Save to Sanity
    const quote = await sanity.create({
      _type: "quote",
      fullName,
      phoneNumber,
      serviceRequired,
      additionalInfo,
    });

    // ✅ Send email
    const emailResponse = await resend.emails.send({
      from: "Rapid Auto Rescue <rapidautorescue@resend.dev>",
      to: "autosaleslogisticsltd@gmail.com", // your email
      subject: `🚨 New Quote Request from ${fullName}`,
      html: `
      <div style="font-family: Arial, sans-serif; color: #333;">
        <img
          src="https://res.cloudinary.com/dmvd50ydu/image/upload/v1751306309/logo-fortune_waav9u.png"
          alt="Rapid Auto Rescue Logo"
          style="max-width: 150px; display: block; margin: 0 auto;"
          width="150"
        />
        <h2 style="text-align: center;">New Quote Request</h2>
        <p><strong>Name:</strong> ${fullName}</p>
        <p><strong>Phone:</strong> ${phoneNumber}</p>
        <p><strong>Service:</strong> ${serviceRequired}</p>
        <p><strong>Details:</strong> ${additionalInfo}</p>
        <hr />
        <p style="font-size: 12px; color: #888; text-align: center;">
          This email was generated by RapidAutoRescue.co.uk
        </p>
      </div>
    `,
    });

    console.log("📧 Email sent via Resend:", emailResponse);

    res.status(201).json({ message: "Quote created", quote });
  } catch (error) {
    console.error("❌ Quote submission failed:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/contact", async (req, res) => {
  const { name, email, message } = req.body;

  try {
    const contact = await sanity.create({
      _type: "contact",
      name,
      email,
      message,
    });

    await resend.emails.send({
      from: "Rapid Auto Rescue <rapidautorescue@resend.dev>",
      to: "autosaleslogisticsltd@gmail.com",
      subject: "📬 New Contact Message Received",
      html: `
          <div style="font-family: Arial, sans-serif; padding: 24px; background-color: #f3f4f6; color: #1f2937;">
            <img src="https://res.cloudinary.com/dmvd50ydu/image/upload/v1751306309/logo-fortune_waav9u.png" alt="Rapid Auto Rescue" style="width: 150px; margin-bottom: 20px;" />
            <h2 style="color: #1f2937;">New Contact Message</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Message:</strong><br/> ${message}</p>
            <hr style="margin: 20px 0;" />
            <p style="font-size: 14px; color: #6b7280;">Submitted via <a href="https://www.rapidautorescue.co.uk" style="color: #2563eb;">RapidAutoRescue.co.uk</a> on ${new Date().toLocaleString()}</p>
          </div>
        `,
    });

    res.status(201).json({ message: "Contact message sent", contact });
  } catch (error) {
    console.error("❌ Contact submission failed:", error.message);
    res.status(500).json({ error: error.message });
  }
});

// ✅ Send Email Notification

// ✅ Start server
app.listen(PORT, () => {
  console.log(`Booking API server running on http://localhost:${PORT}`);
});
